name: Test setup-node caching
on: [workflow_dispatch]
jobs:
  run:
    name: Node test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [macos-latest]
        version: [ '12.x', '14.x', '16.x' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: actions/cache@v2
      with:
        path: /Users/runner/.npm
        key: ${{ runner.os }}-test-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-test-
          ${{ runner.os }}-
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.version }}
    - name: Install dependencies
      run: npm install
