name: Test setup-node caching
on: [push, workflow_dispatch]
jobs:
  run:
    name: Node test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-18.04, macos-latest, windows-latest]
        version: [ '12.x' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: jacobwgillespie/setup-node@cache-pnpm # dmitry-shibanov/setup-node@v-dmshib/test-silent
      with:
        node-version: ${{ matrix.version }}
        cache: npm
    - name: Node version
      shell: pwsh
      run: node --version
    - name: Yarn version
      run: yarn --version
    - name: Npm version
      shell: pwsh
      run: npm --version
    - name: Install dependencies
      run: npm install
