name: Test setup-node caching
on: [workflow_dispatch]
jobs:
  run:
    name: Node test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-18.04, macos-latest, windows-latest]
        version: [ '12.x' ]
        cache: [ npm, pnpm, yarn ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: npm install -g pnpm
    - uses: jacobwgillespie/setup-node@cache-pnpm
      with:
        node-version: ${{ matrix.version }}
        cache: ${{ matrix.cache }}
    - name: Node version
      shell: pwsh
      run: node --version
    - name: Yarn version
      run: yarn --version
    - name: Npm version
      shell: pwsh
      run: npm --version
    - name: Install dependencies
      run: npm install
